# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

# Minecraft and Forge versions for 1.20.1
minecraft_version=1.20.1
forge_version=47.3.0

# Parchment mappings
parchment_version=2023.09.03

# Mod Properties
mod_id=instantworldmirror
mod_name=World Mirrors
mod_license=All Rights Reserved
mod_version=1.2.2-Beta-dev.2
mod_group_id=com.crabmods.instantworldmirror
mod_authors=CrabMods
