# This is a mods.toml file for Forge 1.20.1
modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"
issueTrackerURL=""

[[mods]]
modId="instantworldmirror"
version="${file.jarVersion}"
displayName="World Mirrors"
updateJSONURL="https://raw.githubusercontent.com/crabsatellite/InstantWorldMirror/changelog/changelog.json"
displayURL=""
logoFile="logo.png"
credits=""
authors="CrabMods"
description='''
World Mirrors - A mod by CrabMods
Allows players to enter a mirrored copy of the world.
'''

[[mixins]]
config="instantworldmirror.mixins.json"

[[dependencies.instantworldmirror]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.instantworldmirror]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
